const state = {
  user: null,
  error: null,
  success: null,
  status:null,
  role: null,
  type:null,
  ukey:null,
  username:null,
  avatarImg:null,
  dob:null,
  userstatus:null,
  coverImg:null,
  location:null,
  unseenNoti:null,
  unseenMessage:0,
  currentContact:0,
  messagesData:[],
  postsData:[],
  filterPosts:[],
};
export default state;
